# Generated by Django 2.2.7 on 2020-01-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='games.Game'),
        ),
    ]
