# Generated by Django 2.2.7 on 2020-01-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_transaction_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='profile',
            new_name='developer',
        ),
    ]
