# Generated by Django 2.2.7 on 2020-01-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gamepurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('start', 'start'), ('succes', 'succes'), ('cancel', 'cancel'), ('error', 'error')], default='start', max_length=20),
        ),
    ]
