# Generated by Django 2.2.7 on 2020-02-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('start', 'start'), ('saved', 'saved'), ('finished', 'finished')], default='start', max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='state',
            field=models.TextField(),
        ),
    ]
