# Generated by Django 2.2.7 on 2020-02-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20200207_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(default='start', max_length=10),
        ),
    ]
